language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$PASSWORD" | docker login -u pflqq --password-stdin
  - docker build -t pflqq/fe-demo:latest .
  - docker push  pflqq/fe-demo:latest